### ISSUE TITLE
Instructions for RSS

### ISSUE THREAD

**Issue by mickesv** [morea-framework/basic-template#1]
Might I humbly suggest that you in the instructions for how to connect an RSS feed to a news page also add that the preamble in `feed.xml` should have `layout: none`, otherwise the XML will not be rendered properly and will not be loadable by any RSS reader.

**Comment by philipmjohnson** [comment]
Thanks!  Just committed the change to basic-template.  Actually I changed it to `layout: null` which I believe to be the appropriate value to disable layout.
