### ISSUE TITLE
themes not loading on GH but looks fine running local

### ISSUE THREAD

**Issue by lipyeow** [morea-framework/basic-template#2]
I am not sure if I messed up something, but my ics491f17 site looks fine when doing "run-local", but it doesn't look fine when published on GH. I tried different themes and the result is the same.

https://lipyeow.github.io/ics491f17/

Any ideas ?

Lipyeow

**Comment by philipmjohnson** [comment]
Does this help?

https://stackoverflow.com/questions/31214534/why-does-my-morea-site-look-ok-locally-but-not-when-published

**Comment by henricasanova** [comment]
Hopefully this has helped Lipyeow. This trips me up every time, somehow :)

Henri

**Comment by lipyeow** [comment]
changing the baseurl was one of the things i tried yesterday (coz i discovered it via a "diff" with a working morea site), but it still did not fix the problem after doing "publish". 

Let me know if you have any suggestions on what to check or try. Otherwise i can try to catch you sometime this afternoon if you're in school.

Lipyeow

**Comment by philipmjohnson** [comment]
Can you make me a collaborator with push privileges on that repo? then I can fiddle around with it this weekend or early next week.  I won't be in school today, unfortunately.

**Comment by lipyeow** [comment]
Guys, I think i fixed it by removing all the morea scripts and downloading the latest "scripts" from the morea framework repo.
